### ISSUE TITLE
How to use specific format

### ISSUE THREAD

**Issue by fanadol** [rylio/ytdl#101]
Hi, is there a way to use specific itag that is not returned from `GetVideoInfo` ?

I want to play live stream video from youtube and stream it to discord (sound only for bot). AFAIK i need to use `itags 92, 93, ...`, but the result from `GetVideoInfo` does not include that `itags`.

Thanks

**Comment by corny** [comment]
This project is not maintained any more. Please switch to https://github.com/kkdai/youtube
