### ISSUE TITLE
Remove my test tags from your repo

### ISSUE THREAD

**Issue by Andreychik32** [rylio/ytdl#110]
As you merged my PR #109, my test tags from my fork [Andreychik32/ytdl](https://github.com/andreychik32/ytdl) was added to your repo (is this a github bug?).

You need to remove them, as they may break your versioning policy.
![image](https://user-images.githubusercontent.com/14360752/88185999-4f13f200-cc3d-11ea-9201-07b7b05ce3a9.png)
https://github.com/rylio/ytdl/tags

**Comment by corny** [comment]
Oh my dear, I didn't realize I pushed all your tags. Luckily I was able to remove them. Thanks for your awareness!

**Comment by Andreychik32** [comment]
I just can't understand why this happened. Am I done something wrong? Just asking for my own experience, because this is my first PR to open-source repo :D

**Comment by corny** [comment]
I added your repository as another remote to my local repository and did a `git fetch`. Then I automatically pulled your tags and I pushed them all with `git push --tags`.
