### ISSUE TITLE
Error when running go get 

### ISSUE THREAD

**Issue by greentornado** [rylio/ytdl#112]
<img width="432" alt="Screen Shot 2020-07-28 at 3 02 20 PM" src="https://user-images.githubusercontent.com/280004/88636644-65a9c580-d0e3-11ea-8722-5f383924e2d2.png">

I got this error when running go get, please check :D

**Comment by steadylearner** [comment]
I have exactly same problem. Please, solve this.

**Comment by pemmenegger** [comment]
Same here

**Comment by greentornado** [comment]
Please read this [link](https://github.com/kkdai/youtube/pull/96), this pkg is deprecated
I have moved to https://github.com/kkdai/youtube

**Comment by corny** [comment]
I did the last bugfixes and improvements in ytdl and I won't work on this project any more. Consider ytdl as being deprecated.
Instead I put my effort in https://github.com/kkdai/youtube

**Comment by corny** [comment]
This project is not maintained any more.
