### ISSUE TITLE
Error parsing signature tokens

### ISSUE THREAD

**Issue by ljgago** [rylio/ytdl#25]
Hello, I am using you lib in a music bot and today appeared an error at getting the url:
"Error parsing signature tokens".
Also I test the ytdl client and have the same error:

Example: ./ytdl -u https://www.youtube.com/watch?v=8TTTcVHNvrc
"Unable to get download url: Error parsing signature tokens"

Did youtube change something?

Thanks.

**Comment by rylio** [comment]
I believe this is because the content is not available in your location, as it is for me in the United States.

**Comment by fent** [comment]
Might be the same issue as https://github.com/fent/node-ytdl-core/issues/158

**Comment by ljgago** [comment]
I have been using ytdl for more than a month without problems.
This happened yesterday or today.
The locate inssue can't be because these videos I can see it in the browser.
There will be some changes youtube by what they say in fent/node-ytdl-core#158
Thanks.

**Comment by FireController1847** [comment]
@ljgago Are you updated to the latest commit (1.14.1)? That should fix your issue.

**Comment by ljgago** [comment]
@FireController1847 yes, I removed _$GOPATH/src/github.com/rylio/ytdl_, run _go get github.com/rylio/ytdl_, and I build the cmd app today, and it work with same issue

**Comment by ljgago** [comment]
Today I test again, and it is working fine now.
It may have been a temporary youtube problem.
Thanks!
