### ISSUE TITLE
worst audio not working

### ISSUE THREAD

**Issue by porjo** [rylio/ytdl#28]
For a specific video, the list of formats returned does not include worst audio format (compared with `youtube-dl` which does include this). 
```
./ytdl -f worst-audio https://www.youtube.com/watch?v=xwx4QzEAKKw
````

This results in the highest quality video being downloaded!

**Comment by rylio** [comment]
Hi @porjo, I no longer have time to maintain this project, but fill free to fix the issue yourself and submit a pull request

**Comment by porjo** [comment]
I've had a go fixing this in my branch [here](https://github.com/rylio/ytdl/compare/master...porjo:extremes) but I'm not sure if this is the correct approach. The `TestExtremes` test case fails with this modification.

 It's unclear to me what `FormatList.Extremes()` is meant to do. Should it return all non zero values in sorted order?

**Comment by corny** [comment]
This project is not maintained any more. Please switch to https://github.com/kkdai/youtube
