### ISSUE TITLE
Addition of -mp3 flag

### ISSUE THREAD

**Issue by kishaningithub** [rylio/ytdl#35]
If ffmpeg is available in the system the flag `-mp3` will convert the downloaded video into mp3

### Example

```bash
ytdl -mp3 'https://www.youtube.com/watch?v=9bZkp7q19f0'
```

If you are fine with this i am willing to do it and create a PR

**Comment by corny** [comment]
This project is not maintained any more. Please switch to https://github.com/kkdai/youtube
