### ISSUE TITLE
Error parsing signature tokens on 30% of videos.

### ISSUE THREAD

**Issue by AlmightyFloppyFish** [rylio/ytdl#38]
using the ytdl binary like:
`./ytdl -u`
or using ytdl in code, has the same issue. On random videos i get this error

_When using for example:_
` ./ytdl https://www.youtube.com/watch?v=YqUyNvGsM9s`
I get this:
`FATA[0000] Unable to get download url: Error parsing signature tokens`

Or when using in Go Code:
`panic: Error parsing signature tokens`

I have reproduced this on Windows 10, Void Linux and Arch Linux.

Videos that do work 
> https://www.youtube.com/watch?v=1gOQiFEwnZ8
> https://www.youtube.com/watch?v=MXgnIP4rMoI
> https://www.youtube.com/watch?v=peBgUMT26jM

Videos that don't work
> https://www.youtube.com/watch?v=aQZDbBGBJsM
> https://www.youtube.com/watch?v=cRS4mS4gKwg
> https://www.youtube.com/watch?v=0fllyJTBsRU

I have been unable to find any pattern.

**Comment by yalay** [comment]
you can see this, I fixed it using a stupid way.
https://github.com/yalay/ytdl

https://github.com/yalay/ytdl/commit/ef685f9a9bf23714f0481260774000e0baf28c95

**Comment by AlmightyFloppyFish** [comment]
@yalay Tried it but it made no difference to me...

**Comment by yalay** [comment]
@AlmightyFloppyFish you can try this, https://github.com/rylio/ytdl/pull/39 , looks like a good way.

**Comment by yalay** [comment]
@AlmightyFloppyFish o, you have seen it.
