### ISSUE TITLE
GetVideoInfo needs url sanitizing/validation

### ISSUE THREAD

**Issue by Strum355** [rylio/ytdl#43]
Currently, anything can be passed to `GetVideoInfo`, and a `*VideoInfo` will be returned, regardless whether or not the passed string is a valid YouTube video link or not. 
For example, if i pass `if` to `GetVideoInfo`, i will be given a `*VideoInfo` without an error being returned. I can call `Download` on this too and no error is returned from this either, even though its not a valid YouTube video

The returned `*VideoInfo`:
```
&{if   0001-01-01 00:00:00 +0000 UTC [] []  0s /yts/jsbin/player-vflHDhBq1/en_US/base.js}
```

**Comment by BruceWangNo1** [comment]
If you didn't know it, your example argument "if" to function "GetVideoInfo" could be a video id, though I think most Youtube video IDs are 11 characters in length. @Strum355

**Comment by Strum355** [comment]
@BruceWangNo1 yea i recall that much, however i followed the links that ytdl went through and they resulted in invalid pages, however ytdl didnt return an error there

**Comment by BruceWangNo1** [comment]
It's funny that when we pass "https://www.youtube.com/watch?v=if" as HTTP request url, Youtube responds OK with a page without any page.  @Strum355

**Comment by BruceWangNo1** [comment]
If we run this project from command line, there would be an error saying "No formats available that match criteria", so I assume you are using this project as a library. Is that correct?

**Comment by Strum355** [comment]
Yea i believe thats all i can really do for now @BruceWangNo1

**Comment by corny** [comment]
This behaviour should not exist any more in the current version.
