### ISSUE TITLE
Playlist Support

### ISSUE THREAD

**Issue by kylescottmcgill** [rylio/ytdl#5]
Are you going for the "Unix" type flow, where we would pass in multiple Video Id's. Or do you think Playlist support would be ideal in this? I'm willing to look into this over the weekend - unless you already have :), just wanted to know your thoughts on this.

**Comment by otium** [comment]
I'm planning on having the option to pass multiple video ids, but I want to keep it lightweight so playlists aren't going to be implemented.

**Comment by kylescottmcgill** [comment]
Excellent, thanks for replying so quickly :)

**Comment by cking** [comment]
As a workaround, you could use:
```go
		client := &http.Client{Transport: &transport.APIKey{Key: youtubeApiKey}}
		service, err := youtube.New(client)
		if err != nil {
			return // failed to connect to google api
		}

		url, err := url.Parse(playlistLink)
		if err != nil {
			// malformed url
			return
		}
		call := service.PlaylistItems.List("id,snippet").PlaylistId(url.Query().Get("list")).MaxResults(50)
		response, err := call.Do()
		if err != nil {
			return // failed to find playlist
		}

		results := response.PageInfo.TotalResults // save total results
		err = call.Pages(nil, func(response *youtube.PlaylistItemListResponse) error {
			for _, vid := range response.Items {
				// query youtube video
				md, err := ytdl.GetVideoInfo("https://youtube.com/watch?v=" + vid.Snippet.ResourceId.VideoId)
				if err != nil {
					// ytdl error, either
					continue
					// or
					// return err
				}

				results--
			}

			return nil
		})

		// results holds the number of failed queries
```

**Comment by kylescottmcgill** [comment]
haha, thanks cking, i had a similar patch to this as well :+1: 

Unless @rylio wants to keep this open for multiple ID's i think this could be closed

**Comment by rylio** [comment]
I currently don't have the time and motivation to work on this, but maybe in the future I will add it. So I am going to keep it open

**Comment by corny** [comment]
This project is not maintained any more. Please switch to https://github.com/kkdai/youtube
