### ISSUE TITLE
Different language titles

### ISSUE THREAD

**Issue by Chiiruno** [rylio/ytdl#54]
If we have a server based in say, France, ytdl will get the French title.
A way to specify what language we want our response to be in would be nice.
I think `https://www.youtube.com/get_video_info?video_id=${ID}` gets the default title that the uploader uses, if nothing else.

**Comment by Chiiruno** [comment]
No, it's still by IP.
Is there any way to override YouTube's language-by-IP bullshit?

**Comment by corny** [comment]
The latest version adds `Accept-Language: en-US,en;q=0.5` to the header.

**Comment by corny** [comment]
This project is not maintained any more. Please switch to https://github.com/kkdai/youtube
