### ISSUE TITLE
Support almost all possible youtube url formats

### ISSUE THREAD

**Issue by nilsocket** [rylio/ytdl#60]
https://www.youtube.com/embed/GxC7llQRovo?list=PLEbnTDJUr_IegfoqO4iPnPYQui46QqT0j
https://www.youtube.com/embed/TbQToa__-bQ
unable to extract video info from this url, and this works 
https://youtu.be/TbQToa__-bQ
https://youtu.be/GxC7llQRovo

Thank you.

**Comment by karthikmuralidharan** [comment]
Also for this: https://youtu.be/GxC7llQRovo

**Comment by corny** [comment]
closed by 5ae23c93da65a75178fe2c6b1447ef4d824666a2

**Comment by lowerzero** [comment]
Also it would be nice if m.youtube.com supported
