### ISSUE TITLE
Go module compatibility

### ISSUE THREAD

**Issue by jostyee** [rylio/ytdl#61]
Currently `go mod` would download the latest release 0.5.1, which imports `github.com/Sirupsen/logrus` as a dependency, for which would make go build complaining a conflict. Have to modify go.mod to specify master branch to workaround this issue, please release a new tag to fix, thanks in advance.

**Comment by andersfylling** [comment]
Have the same issue here. Why has this not yet been fixed? Is the project dead?

**Comment by pieterclaerhout** [comment]
+1

**Comment by paolobarbolini** [comment]
Still waiting on this. Why hasn't there been a release in the last 2 years?

**Comment by cbluth** [comment]
put this in your `go.mod` file

```
replace (
	github.com/Sirupsen/logrus => github.com/sirupsen/logrus v1.4.3-0.20190807103436-de736cf91b92
)
```

**Comment by corny** [comment]
Please try the latest tag `v0.6.0`.
