### ISSUE TITLE
Zero bytes

### ISSUE THREAD

**Issue by brydavis** [rylio/ytdl#69]
I'm getting files with appropriate titles but zero bytes.
No errors.
I tried `go get -u` to no avail.
Not sure what's not working.
Thanks

**Comment by schollz** [comment]
I am also seeing this. I can add a little more info.

I am using this library with [getsong](https://github.com/schollz/getsong) and I have a TravisCI cron job to test it daily. I've been getting daily build errors since 06/05/2019 on the same commit (`d71b9ef8`) which is a commit that is over 8 weeks old.

I have some logs and this is what I see when it errors:

```
2019-06-05 19:09:59 [DEBUG] getsong.go downloadYouTube:192 downloading https://r1---sn-vgqskn7e.googlevideo.com/videoplayback?c=WEB&clen=3884052&dur=218.721&ei=hhP4XMCpOpTbNvXXo-gE&expire=1559783399&fvip=1&gcr=us&gir=yes&id=o-AKPffesLG3FdY60IpiLYkR4ugslA9xKiPRMvBlCBjZCk&initcwndbps=4952500&ip=35.188.1.99&itag=251&keepalive=yes&lmt=1533732061734022&lsig=AHylml4wRAIgMOo0Zsu-UluvU0RGgDqbF6VlS5DWVsqaNp4Evu7LGosCIGYyS0W0YubVmYGYw30tDrBewYSZwGY4fajE7CHPVRgw&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps&mime=audio%2Fwebm&mm=31%2C29&mn=sn-vgqskn7e%2Csn-vgqsrn7d&ms=au%2Crdu&mt=1559751098&mv=m&pl=20&ratebypass=yes&requiressl=yes&signature=ALgxI2wwRQIgVimHksAkYAakM-tSG8n4s1QsgWJMiOUUGFOcz6ttbvgCIQDTZ4V9T1J0X0NQtpd2sglByGivBoxqkjjKHiM0nAs7YQ%3D%3D&source=youtube&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt 
2019-06-05 19:09:59 [DEBUG] getsong.go DownloadFromYouTube:215 total length: 0 
...converting to mp3...
--- FAIL: TestGetSongAPI (1.57s)
    getsong_test.go:19: 
        	Error Trace:	getsong_test.go:19
        	Error:      	Expected nil, but got: could not convert video: exit status 1
        	Test:       	TestGetSongAPI
```

Basically its showing that it gets a good URL but that it downloads zero bytes. Eventually an error is thrown in my program because it tries to convert a file that is empty and then the Travis test fails.

I've seen that this problem is not consistent. I fixed my program by just re-trying grabbing the YT URL if it does fail with getting a zero-length file, because sometimes it does not get a zero-length file. Its weird.

**Comment by sula7** [comment]
I tried to use this repo in OS windows (7, 10) and different hardware and I've got 0 byte files. When I tried to use it in linux (ubuntu 18.04), it works properly. Golang ver 1.12.6 in all PCs.
@rylio maybe need to test and write to readme that this works only in linux?

**Comment by danackerson** [comment]
Also have the issue. From this share URL: https://youtu.be/WlGiOiRQNhI **ytdl** generates

https://r1---sn-h0jeeney.googlevideo.com/videoplayback?c=WEB&clen=10034172&dur=179.141&ei=SB40XZ6rKs7pgAeg2pfYDA&expire=1563718312&fvip=1&gir=yes&id=o-ANXtxUe5azceiR_tbMhqARhtg0CYDzkUYYm8NcQMdQBG&initcwndbps=1135000&ip=91.42.93.122&itag=18&lmt=1556819171250276&lsig=AHylml4wRAIgYNmudzIIf-N6jlo-OXWJoe0yGvMbs55E60PtGLMfTzACIAfOak3U7FkOuXOoylFpVhKpbOVGpmqhai63vgS_8Uds&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&mime=video%2Fmp4&mm=31%2C26&mn=sn-h0jeeney%2Csn-4g5ednld&ms=au%2Conr&mt=1563696576&mv=m&mvi=0&pl=26&ratebypass=yes&requiressl=yes&signature=ALgxI2wwRQIhANBeJOmd2lKkTps7lHv_FPHtLThbbD7zacryuIeMuEpDAiAG1Wt-jiISybTtUgBN3ncD14yCUVTWvStk3DbB628_FQ%3D%3D&source=youtube&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&txp=5531432

which results in:
```
HTTP/1.1 403 Forbidden
Last-Modified: Wed, 02 May 2007 10:26:10 GMT
Content-Type: text/plain
Content-Length: 0
Connection: close
X-Content-Type-Options: nosniff
Date: Sun, 21 Jul 2019 08:20:04 GMT
Server: gvs 1.0
```

**Comment by danackerson** [comment]
grab another video: https://youtu.be/huN34U2rmvs **ytdl** generates

https://r6---sn-h0jeen76.googlevideo.com/videoplayback?c=WEB&dur=192.818&ei=RiI0XbvdOtap7gPho6X4AQ&expire=1563719335&fvip=1&id=o-AN7dZk6y87KvB8NKv8PA1BJYrvoj0jwX05vnIrc_coBR&initcwndbps=1146250&ip=91.42.93.122&itag=22&lmt=1563646322257900&lsig=AHylml4wRAIgGDl9GMQlGNnoAbxA4TEenXx7xE7iY3oNJoqc3ALcIFwCIB8n9nunQwwRIs2ORDRIX7kIJaC-jrtnsU5txO6Q7-Hh&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&mime=video%2Fmp4&mm=31%2C26&mn=sn-h0jeen76%2Csn-4g5e6nzz&ms=au%2Conr&mt=1563697625&mv=m&mvi=5&pl=26&ratebypass=yes&requiressl=yes&sig=ALgxI2wwRQIgGPb7G6h58uo_voTiaA4B9Qv70XshUMS-cgXTkO876E4CIQDrv8n8PsSjG0iouSQVTkUJAKbQvXK3x7FJoIlbxv5CyQ%3D%3D&source=youtube&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&txp=2316222

HTTP 200 all fine.

**Comment by danackerson** [comment]
see #70 - Youtube changed API to use `?sig=` instead of `?signature=`

**Comment by corny** [comment]
This necessary change has been pushed into the master branch.
