### ISSUE TITLE
Update logrus github path

### ISSUE THREAD

**Issue by xyaman** [rylio/ytdl#74]
`github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod:
        module declares its path as: github.com/sirupsen/logrus
                but was required as: github.com/Sirupsen/logrus`

Can you update the import path?

**Comment by zikaeroh** [comment]
See #61. It's fixed, but since the repo hasn't had a tag in a long time, you'll have to `go get github.com/rylio/ytdl@master` to move past the fix.
