### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by mihaiav** [rylio/ytdl#79]
../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:47:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:52:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:56:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:60:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:64:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:68:22: cannot use cli.StringSliceFlag literal (type cli.StringSliceFlag) as type cli.Flag in slice literal:
	cli.StringSliceFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:72:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:76:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:80:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:84:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:84:17: too many errors

**Comment by corny** [comment]
Which Go version are you using? If it is not 1.13, please upgrade.
