### ISSUE TITLE
Dont compile last version (go get -u github.com/rylio/ytdl/...)

### ISSUE THREAD

**Issue by JAVIERCUADROS7** [rylio/ytdl#86]
# github.com/rylio/ytdl/cmd/ytdl
../../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:51:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:56:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:60:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:64:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:68:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:72:22: cannot use cli.StringSliceFlag literal (type cli.StringSliceFlag) as type cli.Flag in array or slice literal:
	cli.StringSliceFlag does not implement cli.Flag (Apply method has pointer receiver)
../../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:76:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:80:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:84:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:88:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../../go/src/github.com/rylio/ytdl/cmd/ytdl/main.go:88:17: too many errors

**Comment by corny** [comment]
This has stopped working since the migration of Go modules. See also https://github.com/golang/go/issues/24250
To compile ytdl:
```bash
git clone git@github.com:rylio/ytdl.git
cd ytdl
go build ./cmd/ytdl
```
The binary is created in the current directory.

**Comment by wedojava** [comment]
> This has stopped working since the migration of Go modules. See also [golang/go#24250](https://github.com/golang/go/issues/24250)
> To compile ytdl:
> 
> ```shell
> git clone git@github.com:rylio/ytdl.git
> cd ytdl
> go build ./cmd/ytdl
> ```
> 
> The binary is created in the current directory.

Thanks, this worked for me.

**Comment by wedojava** [comment]
@JAVIERCUADROS7 Hi, this worked for me: `GO111MODULE=on go get -u -ldflags "-s -w" github.com/corny/ytdl/...`

**Comment by shoce** [comment]
```
; rm -rf $HOME/src/github.com/rylio/ytdl 

; go get -u github.com/rylio/ytdl/...
# github.com/rylio/ytdl/cmd/ytdl
src/github.com/rylio/ytdl/cmd/ytdl/main.go:51:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
src/github.com/rylio/ytdl/cmd/ytdl/main.go:56:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
src/github.com/rylio/ytdl/cmd/ytdl/main.go:60:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
src/github.com/rylio/ytdl/cmd/ytdl/main.go:64:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
src/github.com/rylio/ytdl/cmd/ytdl/main.go:68:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
src/github.com/rylio/ytdl/cmd/ytdl/main.go:72:22: cannot use cli.StringSliceFlag literal (type cli.StringSliceFlag) as type cli.Flag in slice literal:
	cli.StringSliceFlag does not implement cli.Flag (Apply method has pointer receiver)
src/github.com/rylio/ytdl/cmd/ytdl/main.go:76:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
src/github.com/rylio/ytdl/cmd/ytdl/main.go:80:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
src/github.com/rylio/ytdl/cmd/ytdl/main.go:84:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
src/github.com/rylio/ytdl/cmd/ytdl/main.go:88:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
src/github.com/rylio/ytdl/cmd/ytdl/main.go:88:17: too many errors


; cd $HOME/src/github.com/rylio/ytdl


; go build -o $HOME/bin/ytdl ./cmd/ytdl
# github.com/rylio/ytdl/cmd/ytdl
cmd/ytdl/main.go:171:34: not enough arguments in call to client.GetVideoInfo
	have (string)
	want (context.Context, interface {})
cmd/ytdl/main.go:248:43: not enough arguments in call to client.GetDownloadURL
	have (*ytdl.VideoInfo, *ytdl.Format)
	want (context.Context, *ytdl.VideoInfo, *ytdl.Format)
```

**Comment by r-novel** [comment]
@shoce PR: https://github.com/rylio/ytdl/pull/96

**Comment by JAVIERCUADROS7** [comment]
Hi everybody, could you help me to solve this issue.
Some weeks ago I can run without problems but today I find this problem.



*{"level":"debug","time":"2020-04-23T10:13:57-05:00","message":"Fetching
https://www.youtube.com/watch?v=WkVvG4QTO9M
<https://www.youtube.com/watch?v=WkVvG4QTO9M>"}Failed to get video info*

**Comment by corny** [comment]
Please try the latest release.
