### ISSUE TITLE
GetVideoInfo - invalid character ';' after top-level value

### ISSUE THREAD

**Issue by f1l0** [rylio/ytdl#89]
Hi,
sometimes when I you the GetVideoInfo function I get the following error:
GetVideoInfo key:[https://www.youtube.com/watch?v=ySlZdASmGCM&list=PL8bO0_lRQOdjEr7tgbsgDOgbVv_zw1o_L]: invalid character ';' after top-level value
(it happen also for a normal video url)

**Comment by fanadol** [comment]
Hi, i also got the same issue, any info about this ?

**Comment by jamestjw** [comment]
I can confirm that this is happening, did youtube change their video info payload or something?

**Comment by fanadol** [comment]
it looks like the error occur when trying to unmarshal in [here](https://github.com/rylio/ytdl/blob/v0.6.2/video_info.go#L166), but i cannot understand the purpose of that code.

**Comment by corny** [comment]
Please try again with the latest release.
