### ISSUE TITLE
Add MKV support

### ISSUE THREAD

**Issue by prologic** [rylio/ytdl#91]
It would appear (See kkdai/youtube#20) your library doesn't support some Youtube videos in MKV? format either.

See [this comment](https://github.com/kkdai/youtube/issues/20#issuecomment-605764128)

```#!sh
$ ytdl https://www.youtube.com/watch?v=FHpvI8oGsuQ
{"level":"info","time":"2020-03-30T13:32:02+10:00","message":"Fetching video info..."}
{"level":"info","time":"2020-03-30T13:32:03+10:00","message":"Downloading to Milo: Forbidden Conversation.mp4"}
{"level":"fatal","error":"unexpected EOF","time":"2020-03-30T13:32:04+10:00"}
```

Can we get this added/fixed?

**Comment by corny** [comment]
This project is not maintained any more. Please switch to https://github.com/kkdai/youtube
