### ISSUE TITLE
can not download https://youtu.be/Hd_ptbiPoXM

### ISSUE THREAD

**Issue by sunnycamel** [rylio/ytdl#97]
can not download https://youtu.be/Hd_ptbiPoXM

**Comment by danackerson** [comment]
> can not download https://youtu.be/Hd_ptbiPoXM

@sunnycamel would you share the error with us?

If it's "invalid character ';' after top-level value" please upvote https://github.com/rylio/ytdl/issues/89 and KylonRi's fix at https://github.com/KyonLi/ytdl/commit/bdd6b3d0750a894ae4e23ba0501cdd2e2a713513

**Comment by sunnycamel** [comment]
@danackerson that's true,  there is a error message says "invalid character ; xxxx"

**Comment by kkdai** [comment]
It looks like youtube just changes its get profile result. 
Need to update code or all video could not parse

**Comment by corny** [comment]
Please try again with the latest release.
