### ISSUE TITLE
Can not download video

### ISSUE THREAD

**Issue by hikaruchang** [rylio/ytdl#99]
{"level":"info","time":"2020-04-14T23:52:47+08:00","message":"Fetching video info..."}
{"level":"fatal","error":"Unable to fetch video info: invalid character ';' after top-level value","time":"2020-04-14T23:52:49+08:00"}

**Comment by ehsannm** [comment]
There is a regex problem in video_info.go line 129:
`regexpPlayerConfig          = regexp.MustCompile("ytplayer.config = (.*?);ytplayer.load")` 
MUST BE CHANGED TO
`regexpPlayerConfig          = regexp.MustCompile("ytplayer.config = (.*?);ytplayer")`

**Comment by stepan-neretin7** [comment]
actually

**Comment by corny** [comment]
Please try the the latest release.
